package org.rutebanken.tiamat.service.parking;

import org.apache.commons.lang3.StringUtils;
import org.rutebanken.tiamat.auth.UsernameFetcher;
import org.rutebanken.tiamat.model.Organisation;
import org.rutebanken.tiamat.netex.mapping.mapper.NetexIdMapper;
import org.rutebanken.tiamat.repository.OrganisationRepository;
import org.rutebanken.tiamat.versioning.VersionIncrementor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Objects;
import java.util.Optional;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * Creates or updates organisations coming from an import (e.g. GBFS system_information).
 * The netex id of a new organisation is generated by Tiamat, the original id is kept in the imported-id key value.
 */
@Service
@Transactional
public class OrganisationsImportedService {

    private static final Logger logger = LoggerFactory.getLogger(OrganisationsImportedService.class);

    private final OrganisationRepository organisationRepository;
    private final VersionIncrementor versionIncrementor;
    private final UsernameFetcher usernameFetcher;
    private final String validNetexPrefix;

    public OrganisationsImportedService(OrganisationRepository organisationRepository,
                                        VersionIncrementor versionIncrementor,
                                        UsernameFetcher usernameFetcher,
                                        @Value("${netex.validPrefix:MOBIITI}") String validNetexPrefix) {
        this.organisationRepository = organisationRepository;
        this.versionIncrementor = versionIncrementor;
        this.usernameFetcher = usernameFetcher;
        this.validNetexPrefix = validNetexPrefix;
    }

    public Organisation createOrUpdateOrganisation(Organisation incomingOrganisation) {
        Optional<Organisation> existingOrganisation = findExistingOrganisation(incomingOrganisation);
        if (existingOrganisation.isPresent()) {
            return update(incomingOrganisation, existingOrganisation.get());
        }
        return create(incomingOrganisation);
    }

    /**
     * Search order :
     * 1. imported-id key value (organisations created since netex ids are generated by Tiamat)
     * 2. legacy netex id built from the original id (PREFIX:Organisation:originalId)
     * 3. name (legacy behaviour)
     */
    private Optional<Organisation> findExistingOrganisation(Organisation organisation) {
        String originalId = organisation.getOriginalId();
        if (StringUtils.isNotBlank(originalId)) {
            String netexId = organisationRepository.findFirstNetexIdByKeyValue(NetexIdMapper.ORIGINAL_ID_KEY, originalId);
            if (netexId == null) {
                netexId = validNetexPrefix + ":Organisation:" + originalId;
            }
            Organisation found = organisationRepository.findFirstByNetexIdOrderByVersionDesc(netexId);
            if (found != null) {
                return Optional.of(found);
            }
        }
        if (StringUtils.isNotBlank(organisation.getName())) {
            return organisationRepository.findFirstByName(organisation.getName());
        }
        return Optional.empty();
    }

    private Organisation create(Organisation newOrganisation) {
        newOrganisation.setNetexId(null);
        newOrganisation.setCreated(Instant.now());
        newOrganisation.setChangedBy(usernameFetcher.getUserNameForAuthenticatedUser());
        if (StringUtils.isNotBlank(newOrganisation.getOriginalId())) {
            newOrganisation.getOriginalIds().add(newOrganisation.getOriginalId());
        }
        versionIncrementor.initiateOrIncrement(newOrganisation);
        Organisation saved = organisationRepository.save(newOrganisation);
        logger.info("Created organisation {}, version {}, name {}", saved.getNetexId(), saved.getVersion(), saved.getName());
        return saved;
    }

    private Organisation update(Organisation incoming, Organisation existing) {
        boolean updated = false;
        updated |= updateIfDifferent(incoming, existing, Organisation::getName, Organisation::setName);
        updated |= updateIfDifferent(incoming, existing, Organisation::getShortName, Organisation::setShortName);
        updated |= updateIfDifferent(incoming, existing, Organisation::getType, Organisation::setType);
        updated |= updateIfDifferent(incoming, existing, Organisation::getOperator, Organisation::setOperator);
        updated |= updateIfDifferent(incoming, existing, Organisation::getOrganisationUrl, Organisation::setOrganisationUrl);
        updated |= updateIfDifferent(incoming, existing, Organisation::getPurchaseUrl, Organisation::setPurchaseUrl);
        updated |= updateIfDifferent(incoming, existing, Organisation::getPhoneNumber, Organisation::setPhoneNumber);
        updated |= updateIfDifferent(incoming, existing, Organisation::getEmail, Organisation::setEmail);
        updated |= updateIfDifferent(incoming, existing, Organisation::getAndroidStoreUri, Organisation::setAndroidStoreUri);
        updated |= updateIfDifferent(incoming, existing, Organisation::getAndroidDiscoveryUri, Organisation::setAndroidDiscoveryUri);
        updated |= updateIfDifferent(incoming, existing, Organisation::getIosStoreUri, Organisation::setIosStoreUri);
        updated |= updateIfDifferent(incoming, existing, Organisation::getIosDiscoveryUri, Organisation::setIosDiscoveryUri);
        updated |= updateIfDifferent(incoming, existing, Organisation::getLanguage, Organisation::setLanguage);
        updated |= updateIfDifferent(incoming, existing, Organisation::getTimezone, Organisation::setTimezone);

        // Legacy organisations have no imported-id yet
        if (StringUtils.isNotBlank(incoming.getOriginalId()) && existing.getOriginalIds().add(incoming.getOriginalId())) {
            updated = true;
        }

        if (!updated) {
            return existing;
        }

        existing.setChanged(Instant.now());
        existing.setChangedBy(usernameFetcher.getUserNameForAuthenticatedUser());
        versionIncrementor.initiateOrIncrement(existing);
        Organisation saved = organisationRepository.save(existing);
        logger.info("Updated organisation {}, version {}, name {}", saved.getNetexId(), saved.getVersion(), saved.getName());
        return saved;
    }

    private static boolean updateIfDifferent(Organisation incoming, Organisation existing,
                                             Function<Organisation, String> getter, BiConsumer<Organisation, String> setter) {
        String newValue = getter.apply(incoming);
        if (StringUtils.isNotBlank(newValue) && !Objects.equals(newValue, getter.apply(existing))) {
            setter.accept(existing, newValue);
            return true;
        }
        return false;
    }
}
