version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/tiamat
    environment:
      MAVEN_OPTS: -Xmx4G
    steps:
      - checkout
      - run: mvn test -s .circleci/settings.xml