version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.4-jdk-8
        cmd: ["/bin/bash"]
    working_directory: ~/tiamat
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          key: tiamat-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: tiamat-{{ checksum "pom.xml" }}
      - run: mvn test -s .circleci/settings.xml