version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/tiamat
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key:
          - tiamat-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: tiamat-{{ checksum "pom.xml" }}
      - run: mvn -o test -s .circleci/settings.xml