version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.4-jdk-8
        cmd: ["/bin/bash"]
    working_directory: ~/tiamat
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - run: mvn dependency:go-offline -s .circleci/settings.xml
      - run: mvn test -s .circleci/settings.xml