package org.rutebanken.tiamat.changelog;

public enum LoggingActionType {

    PARKING_CREATE("PARKING-CREATE"),
    PARKING_UPDATE("PARKING-UPDATE"),
    PARKING_DELETE("PARKING-DELETE"),
    PARKING_DELETE_ALL("PARKING-DELETE-ALL"),

    POI_CREATE("POI-CREATE"),
    POI_UPDATE("POI-UPDATE"),
    POI_DELETE("POI-DELETE"),
    POI_DELETE_ALL("POI-DELETE-ALL"),

    STOP_PLACE_CREATE("STOP-PLACE-CREATE"),
    STOP_PLACE_UPDATE("STOP-PLACE-UPDATE"),
    STOP_PLACE_DELETE("STOP-PLACE-DELETE"),
    STOP_PLACE_MERGE("STOP-PLACE-MERGE"),
    STOP_PLACE_QUAY_DELETE("STOP-PLACE-QUAY-DELETE"),
    STOP_PLACE_QUAY_MOVE("STOP-PLACE-QUAY-MOVE"),
    STOP_PLACE_RENAME("STOP-PLACE-RENAME"),
    STOP_PLACE_REOPEN("STOP-PLACE-REOPEN"),
    STOP_PLACE_TERMINATION("STOP-PLACE-TERMINATION"),
    STOP_PLACE_DELETE_BY_ORGANISATION("STOP-PLACE-DELETE-BY-ORGANISATION"),

    MULTI_MODAL_STOP_PLACE_CREATE("MULTI-MODAL-STOP-PLACE-CREATE"),
    MULTI_MODAL_STOP_PLACE_UPDATE("MULTI-MODAL-STOP-PLACE-UPDATE"),
    MULTI_MODAL_STOP_PLACE_DELETE("MULTI-MODAL-STOP-PLACE-DELETE"),

    GBFS_PARKING_IMPORT("GBFS-PARKING-IMPORT"),
    BIKE_PARKING_CSV_IMPORT("BIKE-PARKING-CSV-IMPORT"),
    PARKING_CSV_IMPORT("PARKING-CSV-IMPORT"),
    RENTAL_BIKE_CSV_IMPORT("RENTAL-BIKE-CSV-IMPORT"),
    POI_CSV_IMPORT("POI-CSV-IMPORT"),
    STOP_PLACE_NETEX_IMPORT("STOP-PLACE-NETEX-IMPORT"),
    TAD_CSV_IMPORT("TAD-CSV-IMPORT"),
    STOP_PLACE_ACCESSIBILITY_UPDATE("STOP-PLACE-ACCESSIBILITY-UPDATE"),
    QUAY_ACCESSIBILITY_UPDATE("QUAY-ACCESSIBILITY-UPDATE"),
    POI_NETEX_IMPORT("POI-NETEX-IMPORT"),
    PARKING_NETEX_IMPORT("PARKING-NETEX-IMPORT");

    private final String value;

    LoggingActionType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }
}
